{
 "title": "moviebookingapp-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "API Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=~\".+\",status=~\"2.+\",uri=~\"/api/v1.0/moviebooking.*\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=~\".+\",status!~\"2.+\",uri=~\"/api/v1.0/moviebooking.*\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"moviebookingapp\"} * 100",
     "legendFormat": "moviebookingapp"
    }
   ]
  },
  {
   "title": "GET /api/v1.0/moviebooking/all",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"GET\",status=\"200\",uri=\"/api/v1.0/moviebooking/all\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"GET\",status!=\"200\",uri=\"/api/v1.0/moviebooking/all\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "POST /api/v1.0/moviebooking/register",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"POST\",status=\"200\",uri=\"/api/v1.0/moviebooking/register\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"POST\",status!=\"200\",uri=\"/api/v1.0/moviebooking/register\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "POST /api/v1.0/moviebooking/login",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"POST\",status=\"200\",uri=\"/api/v1.0/moviebooking/login\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"POST\",status!=\"200\",uri=\"/api/v1.0/moviebooking/login\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET /api/v1.0/moviebooking/search",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"GET\",status=\"200\",uri=\"/api/v1.0/moviebooking/movies/search/{movieName}\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"GET\",status!=\"200\",uri=\"/api/v1.0/moviebooking/movies/search/{movieName}\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "POST /api/v1.0/moviebooking/add",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"POST\",status=\"200\",uri=\"/api/v1.0/moviebooking/add\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"POST\",status!=\"200\",uri=\"/api/v1.0/moviebooking/add\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE /api/v1.0/moviebooking/delete/{movieId}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"DELETE\",status=\"200\",uri=\"/api/v1.0/moviebooking/delete/{movieId}\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"DELETE\",status!=\"200\",uri=\"/api/v1.0/moviebooking/delete/{movieId}\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "PUT /api/v1.0/moviebooking/updateStatus",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"PUT\",status=\"200\",uri=\"/api/v1.0/moviebooking/updateStatus\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"moviebookingapp\",method=\"PUT\",status!=\"200\",uri=\"/api/v1.0/moviebooking/updateStatus\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  }
 ]
}